version: '3.8'

services:
  jupyterlab:
    image: jupyter/all-spark-notebook
    container_name: jupyter
    environment:
      - JUPYTER_ENABLE_LAB=yes
      - SPYLON_KERNEL_DISPLAY_NAME="Scala (Spark)"
    ports:
      - 8889:8888
    command:
    - sh
    - -c
    - |
      pip install ipywidgets ipykernel metakernel py4j pandas && 
      pip install "IPython<8.0.0" && 
      pip install pyspark_kernel && 
      python -m pyspark_kernel.installl --user
      jupyter lab --NotebookApp.token=''

    tty: true
    stdin_open: true
    volumes:
      - minio-data:/data

volumes:
  minio-data:
    driver: local
    
networks:
  default:
    name: simple-data-flow
