version: '3'

services:
  spark-master:
    image: apache/spark:3.4.1-scala2.12-java11-python3-r-ubuntu
    container_name: spark-master
    ports:
      - 8080:8080
      - 7077:7077
    environment:
      - INIT_DAEMON_STEP=setup_spark
      - SPARK_MASTER_PORT=7077
      - SPARK_MASTER_WEBUI_PORT=8080
      - SPARK_MASTER_LOG=/spark/logs

  spark-worker-1:
    image: apache/spark:3.4.1-scala2.12-java11-python3-r-ubuntu
    container_name: spark-worker-1
    environment:
      - SPARK_WORKER_PORT=8881
      - SPARK_WORKER_WEBUI_PORT=8081
      - SPARK_WORKER_LOG=/spark/logs
      - SPARK_MASTER_URL=spark://spark-master:7077
    ports:
      - 8081:8081
    depends_on:
      - spark-master

  spark-worker-2:
    image: apache/spark:3.4.1-scala2.12-java11-python3-r-ubuntu
    container_name: spark-worker-2
    environment:
      - SPARK_WORKER_PORT=8881
      - SPARK_WORKER_WEBUI_PORT=8081
      - SPARK_WORKER_LOG=/spark/logs
      - SPARK_MASTER_URL=spark://spark-master:7077
    ports:
      - 8082:8081
    depends_on:
      - spark-master

  spark-worker-3:
    image: apache/spark:3.4.1-scala2.12-java11-python3-r-ubuntu
    container_name: spark-worker-3
    environment:
      - SPARK_WORKER_PORT=8881
      - SPARK_WORKER_WEBUI_PORT=8081
      - SPARK_WORKER_LOG=/spark/logs
      - SPARK_MASTER_URL=spark://spark-master:7077
    ports:
      - 8083:8081
    depends_on:
      - spark-master

  spark-history-server:
    image: apache/spark:3.4.1-scala2.12-java11-python3-r-ubuntu
    container_name: spark-history-server
    ports:
      - 18080:18080
    command: ["history-server"]
    environment:
      - SPARK_HISTORY_OPTS="-Dspark.history.fs.logDirectory=/var/log/spark/event-logs"
    depends_on:
      - spark-master

  jupyterlab:
    image: jupyter/pyspark-notebook
    container_name: jupyterlab
    ports:
      - 8888:8888
    environment:
      - SPARK_MASTER_URL=spark://spark-master:7077
    depends_on:
      - spark-master

networks:
  default:
    name: simple-data-flow
