version: "3.8"

services:
  elasticsearch:
    image: elasticsearch:7.17.10
    container_name: elasticsearch
    environment:
      ES_JAVA_OPTS: "-Xmx256m -Xms256m"
      ELASTIC_PASSWORD: search
    ports:
      - 9201:9200
    volumes:
      - ./src/elk/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
    healthcheck:
      test: ["CMD", "curl", "-f", "http://elasticsearch:9200"]
      interval: 10s
      timeout: 5s
      retries: 5

  logstash:
    image: logstash:7.17.10
    container_name: logstash
    depends_on:
      elasticsearch:
        condition: service_healthy
    environment:
      LS_JAVA_OPTS: "-Xmx256m -Xms256m"
    ports:
      - 5001:5000/tcp
      - 5001:5000/udp
      - 9601:9600
    volumes:
      - ./src/elk/config/logstash.yml:/usr/share/logstash/config/logstash.yml
      - ./src/elk/pipeline:/usr/share/logstash/pipeline
      - ./logs:/usr/share/logstash/logs

  kibana:
    image: kibana:7.17.10
    container_name: kibana
    depends_on:
      elasticsearch:
        condition: service_healthy
    ports:
      - 5601:5601
    volumes:
      - ./src/elk/config/kibana.yml:/usr/share/kibana/config/kibana.yml

networks:
  default:
    name: simple-data-flow
