version: '3.8'

services:
  jupyterlab:
    image: jupyter/all-spark-notebook
    container_name: jupyter
    environment:
      - JUPYTER_ENABLE_LAB=yes
      - SPYLON_KERNEL_DISPLAY_NAME="Scala (Spark)"
    ports:
      - 8889:8888
    command:
    - sh
    - -c
    - |
      pip install spylon-kernel &&
      python -m spylon_kernel install --user
      jupyter lab --NotebookApp.token=''

    tty: true
    stdin_open: true

networks:
  default:
    name: simple-data-flow
